### ISSUE TITLE
Error with Phan ^2 and phan-extensions ^2.4: Undefined class constant 'Phan\Language\Element\Comment::WORD_REGEX'

### ISSUE THREAD

**Issue by Aerendir** [Drenso/PhanExtensions#9]
```yaml
...
    "require-dev": {
        "drenso/phan-extensions": "^2.4",
        "phan/phan": "^2",
        ...
    },
...
```

The error (and stacktrace) is this:

```console
Failed to initialize plugin vendor/drenso/phan-extensions/Plugin/DocComment/InlineVarPlugin.php, exiting: Error: Undefined class constant 'Phan\Language\Element\Comment::WORD_REGEX' at /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/drenso/phan-extensions/Plugin/DocComment/InlineVarPlugin.php:96
Stack Trace:
#0 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Plugin/ConfigPluginSet.php(794): require()
#1 [internal function]: Phan\Plugin\ConfigPluginSet::Phan\Plugin\{closure}('vendor/drenso/p...')
#2 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Plugin/ConfigPluginSet.php(824): array_map(Object(Closure), Array)
#3 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Plugin/ConfigPluginSet.php(198): Phan\Plugin\ConfigPluginSet->ensurePluginsExist()
#4 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Plugin/ConfigPluginSet.php(184): Phan\Plugin\ConfigPluginSet::newInstance()
#5 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Issue.php(4265): Phan\Plugin\ConfigPluginSet::instance()
#6 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Issue.php(4220): Phan\Issue::shouldSuppressIssue(Object(Phan\CodeBase), Object(Phan\Language\Context), 'PhanInvalidComm...', 18, Array, NULL)
#7 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Language/Element/Comment/Builder.php(1310): Phan\Issue::maybeEmitWithParameters(Object(Phan\CodeBase), Object(Phan\Language\Context), 'PhanInvalidComm...', 18, Array, NULL)
#8 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Language/Element/Comment/Builder.php(327): Phan\Language\Element\Comment\Builder->emitDeferredIssues()
#9 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Language/Element/Comment.php(384): Phan\Language\Element\Comment\Builder->build()
#10 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Parse/ParseVisitor.php(410): Phan\Language\Element\Comment::fromStringInContext('/**\n     * @pro...', Object(Phan\CodeBase), Object(Phan\Language\Context), 20, 3)
#11 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Analysis.php(203): Phan\Parse\ParseVisitor->visitPropGroup(Object(ast\Node))
#12 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Analysis.php(230): Phan\Analysis::parseNodeInContext(Object(Phan\CodeBase), Object(Phan\Language\Context), Object(ast\Node))
#13 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Analysis.php(230): Phan\Analysis::parseNodeInContext(Object(Phan\CodeBase), Object(Phan\Language\Context), Object(ast\Node))
#14 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Analysis.php(230): Phan\Analysis::parseNodeInContext(Object(Phan\CodeBase), Object(Phan\Language\Context), Object(ast\Node))
#15 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Analysis.php(158): Phan\Analysis::parseNodeInContext(Object(Phan\CodeBase), Object(Phan\Language\Context), Object(ast\Node))
#16 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/Phan/Phan.php(211): Phan\Analysis::parseFile(Object(Phan\CodeBase), 'vendor/dts/ebay...')
#17 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/src/phan.php(34): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#18 /Users/Aerendir/Documents/JooServer/_Projects/SerendipityHQ/Components/my-library/vendor/phan/phan/phan(2): require_once('/Users/Aerendir...')
#19 {main}
```

**Comment by bobvandevijver** [comment]
@Aerendir I've added Phan 2 support (or at least I hope). Feel free to test some more and report any further issues!
